// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ZooManagement;

#nullable disable

namespace ZooManagement.Migrations
{
    [DbContext(typeof(Zoo))]
    partial class ZooModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ZooManagement.Models.Data.Animal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateOfAcquisition")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Sex")
                        .HasColumnType("integer");

                    b.Property<int>("SpeciesId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SpeciesId");

                    b.ToTable("Animals");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            DateOfAcquisition = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1997, 10, 15, 23, 0, 0, 0, DateTimeKind.Utc),
                            Name = "simba",
                            Sex = 0,
                            SpeciesId = -19
                        },
                        new
                        {
                            Id = -2,
                            DateOfAcquisition = new DateTime(2001, 2, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1997, 9, 9, 23, 0, 0, 0, DateTimeKind.Utc),
                            Name = "nala",
                            Sex = 1,
                            SpeciesId = -19
                        });
                });

            modelBuilder.Entity("ZooManagement.Models.Data.Species", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Classification")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Species");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            Classification = 0,
                            Name = "aardvark"
                        },
                        new
                        {
                            Id = -2,
                            Classification = 0,
                            Name = "antelope"
                        },
                        new
                        {
                            Id = -3,
                            Classification = 0,
                            Name = "bear"
                        },
                        new
                        {
                            Id = -4,
                            Classification = 0,
                            Name = "boar"
                        },
                        new
                        {
                            Id = -5,
                            Classification = 0,
                            Name = "buffalo"
                        },
                        new
                        {
                            Id = -6,
                            Classification = 0,
                            Name = "calf"
                        },
                        new
                        {
                            Id = -7,
                            Classification = 0,
                            Name = "cavy"
                        },
                        new
                        {
                            Id = -8,
                            Classification = 0,
                            Name = "cheetah"
                        },
                        new
                        {
                            Id = -9,
                            Classification = 0,
                            Name = "deer"
                        },
                        new
                        {
                            Id = -10,
                            Classification = 0,
                            Name = "dolphin"
                        },
                        new
                        {
                            Id = -11,
                            Classification = 0,
                            Name = "elephant"
                        },
                        new
                        {
                            Id = -12,
                            Classification = 0,
                            Name = "fruitbat"
                        },
                        new
                        {
                            Id = -13,
                            Classification = 0,
                            Name = "giraffe"
                        },
                        new
                        {
                            Id = -14,
                            Classification = 0,
                            Name = "goat"
                        },
                        new
                        {
                            Id = -15,
                            Classification = 0,
                            Name = "gorilla"
                        },
                        new
                        {
                            Id = -16,
                            Classification = 0,
                            Name = "hamster"
                        },
                        new
                        {
                            Id = -17,
                            Classification = 0,
                            Name = "hare"
                        },
                        new
                        {
                            Id = -18,
                            Classification = 0,
                            Name = "leopard"
                        },
                        new
                        {
                            Id = -19,
                            Classification = 0,
                            Name = "lion"
                        },
                        new
                        {
                            Id = -20,
                            Classification = 0,
                            Name = "lynx"
                        },
                        new
                        {
                            Id = -21,
                            Classification = 0,
                            Name = "mink"
                        },
                        new
                        {
                            Id = -22,
                            Classification = 0,
                            Name = "mole"
                        },
                        new
                        {
                            Id = -23,
                            Classification = 0,
                            Name = "mongoose"
                        },
                        new
                        {
                            Id = -24,
                            Classification = 0,
                            Name = "opossum"
                        },
                        new
                        {
                            Id = -25,
                            Classification = 0,
                            Name = "oryx"
                        },
                        new
                        {
                            Id = -26,
                            Classification = 0,
                            Name = "platypus"
                        },
                        new
                        {
                            Id = -27,
                            Classification = 0,
                            Name = "polecat"
                        },
                        new
                        {
                            Id = -28,
                            Classification = 0,
                            Name = "pony"
                        },
                        new
                        {
                            Id = -29,
                            Classification = 0,
                            Name = "porpoise"
                        },
                        new
                        {
                            Id = -30,
                            Classification = 0,
                            Name = "puma"
                        },
                        new
                        {
                            Id = -31,
                            Classification = 0,
                            Name = "pussycat"
                        },
                        new
                        {
                            Id = -32,
                            Classification = 0,
                            Name = "raccoon"
                        },
                        new
                        {
                            Id = -33,
                            Classification = 0,
                            Name = "reindeer"
                        },
                        new
                        {
                            Id = -34,
                            Classification = 0,
                            Name = "seal"
                        },
                        new
                        {
                            Id = -35,
                            Classification = 0,
                            Name = "sealion"
                        },
                        new
                        {
                            Id = -36,
                            Classification = 0,
                            Name = "squirrel"
                        },
                        new
                        {
                            Id = -37,
                            Classification = 0,
                            Name = "vampire"
                        },
                        new
                        {
                            Id = -38,
                            Classification = 0,
                            Name = "vole"
                        },
                        new
                        {
                            Id = -39,
                            Classification = 0,
                            Name = "wallaby"
                        },
                        new
                        {
                            Id = -40,
                            Classification = 0,
                            Name = "wolf"
                        },
                        new
                        {
                            Id = -41,
                            Classification = 2,
                            Name = "chicken"
                        },
                        new
                        {
                            Id = -42,
                            Classification = 2,
                            Name = "crow"
                        },
                        new
                        {
                            Id = -43,
                            Classification = 2,
                            Name = "dove"
                        },
                        new
                        {
                            Id = -44,
                            Classification = 2,
                            Name = "duck"
                        },
                        new
                        {
                            Id = -45,
                            Classification = 2,
                            Name = "flamingo"
                        },
                        new
                        {
                            Id = -46,
                            Classification = 2,
                            Name = "gull"
                        },
                        new
                        {
                            Id = -47,
                            Classification = 2,
                            Name = "hawk"
                        },
                        new
                        {
                            Id = -48,
                            Classification = 2,
                            Name = "kiwi"
                        },
                        new
                        {
                            Id = -49,
                            Classification = 2,
                            Name = "lark"
                        },
                        new
                        {
                            Id = -50,
                            Classification = 2,
                            Name = "ostrich"
                        },
                        new
                        {
                            Id = -51,
                            Classification = 2,
                            Name = "parakeet"
                        },
                        new
                        {
                            Id = -52,
                            Classification = 2,
                            Name = "penguin"
                        },
                        new
                        {
                            Id = -53,
                            Classification = 2,
                            Name = "pheasant"
                        },
                        new
                        {
                            Id = -54,
                            Classification = 2,
                            Name = "rhea"
                        },
                        new
                        {
                            Id = -55,
                            Classification = 2,
                            Name = "skimmer"
                        },
                        new
                        {
                            Id = -56,
                            Classification = 2,
                            Name = "skua"
                        },
                        new
                        {
                            Id = -57,
                            Classification = 2,
                            Name = "sparrow"
                        },
                        new
                        {
                            Id = -58,
                            Classification = 2,
                            Name = "swan"
                        },
                        new
                        {
                            Id = -59,
                            Classification = 2,
                            Name = "vulture"
                        },
                        new
                        {
                            Id = -60,
                            Classification = 2,
                            Name = "wren"
                        },
                        new
                        {
                            Id = -61,
                            Classification = 1,
                            Name = "pitviper"
                        },
                        new
                        {
                            Id = -62,
                            Classification = 1,
                            Name = "seasnake"
                        },
                        new
                        {
                            Id = -63,
                            Classification = 1,
                            Name = "slowworm"
                        },
                        new
                        {
                            Id = -64,
                            Classification = 1,
                            Name = "tortoise"
                        },
                        new
                        {
                            Id = -65,
                            Classification = 1,
                            Name = "tuatara"
                        },
                        new
                        {
                            Id = -66,
                            Classification = 5,
                            Name = "bass"
                        },
                        new
                        {
                            Id = -67,
                            Classification = 5,
                            Name = "carp"
                        },
                        new
                        {
                            Id = -68,
                            Classification = 5,
                            Name = "catfish"
                        },
                        new
                        {
                            Id = -69,
                            Classification = 5,
                            Name = "chub"
                        },
                        new
                        {
                            Id = -70,
                            Classification = 5,
                            Name = "dogfish"
                        },
                        new
                        {
                            Id = -71,
                            Classification = 5,
                            Name = "haddock"
                        },
                        new
                        {
                            Id = -72,
                            Classification = 5,
                            Name = "herring"
                        },
                        new
                        {
                            Id = -73,
                            Classification = 5,
                            Name = "pike"
                        },
                        new
                        {
                            Id = -74,
                            Classification = 5,
                            Name = "piranha"
                        },
                        new
                        {
                            Id = -75,
                            Classification = 5,
                            Name = "seahorse"
                        },
                        new
                        {
                            Id = -76,
                            Classification = 5,
                            Name = "sole"
                        },
                        new
                        {
                            Id = -77,
                            Classification = 5,
                            Name = "stingray"
                        },
                        new
                        {
                            Id = -78,
                            Classification = 5,
                            Name = "tuna"
                        },
                        new
                        {
                            Id = -79,
                            Classification = 4,
                            Name = "frog"
                        },
                        new
                        {
                            Id = -80,
                            Classification = 4,
                            Name = "newt"
                        },
                        new
                        {
                            Id = -81,
                            Classification = 4,
                            Name = "toad"
                        },
                        new
                        {
                            Id = -82,
                            Classification = 3,
                            Name = "flea"
                        },
                        new
                        {
                            Id = -83,
                            Classification = 3,
                            Name = "gnat"
                        },
                        new
                        {
                            Id = -84,
                            Classification = 3,
                            Name = "honeybee"
                        },
                        new
                        {
                            Id = -85,
                            Classification = 3,
                            Name = "housefly"
                        },
                        new
                        {
                            Id = -86,
                            Classification = 3,
                            Name = "ladybird"
                        },
                        new
                        {
                            Id = -87,
                            Classification = 3,
                            Name = "moth"
                        },
                        new
                        {
                            Id = -88,
                            Classification = 3,
                            Name = "termite"
                        },
                        new
                        {
                            Id = -89,
                            Classification = 3,
                            Name = "wasp"
                        },
                        new
                        {
                            Id = -90,
                            Classification = 6,
                            Name = "clam"
                        },
                        new
                        {
                            Id = -91,
                            Classification = 6,
                            Name = "crab"
                        },
                        new
                        {
                            Id = -92,
                            Classification = 6,
                            Name = "crayfish"
                        },
                        new
                        {
                            Id = -93,
                            Classification = 6,
                            Name = "lobster"
                        },
                        new
                        {
                            Id = -94,
                            Classification = 6,
                            Name = "octopus"
                        },
                        new
                        {
                            Id = -95,
                            Classification = 6,
                            Name = "scorpion"
                        },
                        new
                        {
                            Id = -96,
                            Classification = 6,
                            Name = "seawasp"
                        },
                        new
                        {
                            Id = -97,
                            Classification = 6,
                            Name = "slug"
                        },
                        new
                        {
                            Id = -98,
                            Classification = 6,
                            Name = "starfish"
                        },
                        new
                        {
                            Id = -99,
                            Classification = 6,
                            Name = "worm"
                        });
                });

            modelBuilder.Entity("ZooManagement.Models.Data.Animal", b =>
                {
                    b.HasOne("ZooManagement.Models.Data.Species", "Species")
                        .WithMany()
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Species");
                });
#pragma warning restore 612, 618
        }
    }
}
